server.port=8085
spring.application.name=ratings-data-service

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
spring.config.import=${CONFIG_SERVER_URL}

spring.rabbitmq.host=${RABBITMQ_HOST_URL}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

management.endpoints.web.exposure.include=health, mappings, beans, info

management.tracing.sampling.probability=1
logging.pattern.level=%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]
logging.level.soft.musala.ratingdataservice.resource=DEBUG
