RABBITMQ_HOST_URL=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

CONFIG_SERVER_URL=optional:configserver:http://configuration-server:8081

EUREKA_SERVER_URL=http://discovery-service:8761/eureka
