spring.application.name=user-service
server.port=8082

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:users-db
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.config.import=optional:configserver:http://localhost:8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#CircuteBreaker config
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.circuitbreaker.instances.book-catalog-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.book-catalog-service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.book-catalog-service.wait-duration-in-open-state=1000ms
resilience4j.circuitbreaker.instances.book-catalog-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.book-catalog-service.sliding-window-size=2
resilience4j.circuitbreaker.instances.book-catalog-service.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.book-catalog-service.event-consumer-buffer-size=10
#Retry config
resilience4j.retry.retry-aspect-order=2
resilience4j.retry.instances.book-catalog-service.max-attempts=3
resilience4j.retry.instances.book-catalog-service.wait-duration=2s
resilience4j.retry.instances.book-catalog-service.enable-exponential-backoff=true
resilience4j.retry.instances.book-catalog-service.exponential-backoff-multiplier=5
#Zipkin config
management.tracing.sampling.probability=1
logging.pattern.level=%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]
logging.level.soft.musala.userService.service.UserService=DEBUG
