server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.config.import=${CONFIG_SERVER_URL}

spring.rabbitmq.host=${RABBITMQ_HOST_URL}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

management.endpoints.web.exposure.include=health, mappings, beans, info
